#!/bin/sh

VER="$(grep -Eom1 "@version (([0-9]+)[.])+[0-9]+" aspk.asm)"

TAG="Continuous"
BINARY=target/aspk

gh release delete "$TAG" --yes
gh release create "$TAG" "$BINARY" --title "$TAG" --notes "Assembly Shell Pack v${VER#* } Release - 64bit"

echo "Release '$TAG' criada/atualizada com o binário enviado."
