name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Build ASPK
      run: make
